### ISSUE TITLE
Feed input in at different layers

### ISSUE THREAD

**Issue by skaae** [benanne/Lasagne#100]
I have two types of network input, where I want to feed the second type to the network after the first input has passed through some layers. 

I figure i should use the concat layer to merge the new second input with the intermediate network output, but how do i handle the symbolic variables for the two inputs?

**Comment by benanne** [comment]
`get_output()` can take a dictionary as input, which maps input layers to the desired variables.  So you would call it as: `l_out.get_output({ l_in1: x1, l_in2: x2, ... })` where `x1`, `x2` are Theano expressions / variables.

This is actually one of the few things that's already somewhat documented :) http://lasagne.readthedocs.org/en/latest/modules/layers.html#lasagne.layers.Layer.get_output

**Comment by skaae** [comment]
Ah, Thanks.

**Comment by f0k** [comment]
Alternatively, you can pass in your symbolic variables for the inputs when creating the corresponding input layers (`in1 = InputLayer(your_shape, your_variable)`), and then just call `get_output()` without any further arguments.
