### ISSUE TITLE
Example code to visualize intermediate layers?

### ISSUE THREAD

**Issue by felixlaumon** [benanne/Lasagne#106]
I am trying to optimize the filter size for the convolutional layer and the overall structure. It will be very helpful if the example includes code to visualize the intermediate layers. Similar to http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/filter_visualization.ipynb from caffe.

**Comment by run2** [comment]
I have been trying to do something related. I am pasting some code below - you can use it any way you like it. I am still not very happy with the way I am displaying the kernels. Specially B G R kernels. The plot takes up too much white space and kernels can be barely seen. If you can update it and make it cleaner and more ui friendly - please post back your code. 
I had 32 kernels in my first conv layer

# get the conv kernels into matrices

layers = net.get_all_layers()
layercounter = 0
for l in layers:
    
    if('Conv2DLayer' in str(type(l))):
        f = open('layer' + str(layercounter) + '.weights','wb')
        weights = l.W.get_value()
        weights = weights.reshape(weights.shape[0]*weights.shape[1],weights.shape[2],weights.shape[3])
        #weights[0]
        for i in range(weights.shape[0]):
            wmin = float(weights[i].min())
            wmax = float(weights[i].max())
            weights[i] *= (255.0/float(wmax-wmin))
            weights[i] += abs(wmin)*(255.0/float(wmax-wmin))
        np.save(f, weights)
        f.close()
        layercounter += 1
`
# now load the kernels and display
`
with open('layer0.weights', 'rb') as f:
    layer0 = np.load(f)

fig, ax = plt.subplots(nrows=3, ncols=32, sharex=True, sharey=False)
#sorg = fig.add_subplot(3,32,1)
for i in xrange(1,97):
    #s = fig.add_subplot(3,32,i)
    #s.set_adjustable('box-forced')
    #s.autoscale(False)
    ax[(i-1)/32][(i-1)%32].imshow(layer0[i-1])#,cmap = cm.BLUE,interpolation='bilinear')
    ax[(i-1)/32][(i-1)%32].autoscale(False)
    ax[(i-1)/32][(i-1)%32].set_ylim([0,12])

plt.show()

**Comment by felixlaumon** [comment]
Thanks @run2!

For what's worth, here was my attempt: http://nbviewer.ipython.org/gist/felixlaumon/409692acdecc0921eca6 (prompt 7, 8, 9). I'm using `lasagne.layers.Conv2DLayer`. It's might be actually more useful to find out the sample that maximizes the activation? (as described in http://arxiv.org/pdf/1311.2901v3.pdf)

**Comment by run2** [comment]
Thanks felixlaumon. I will look into this soon.

**Comment by dimatura** [comment]
@felixlaumon personally I would use `interpolation='nearest'` for the `imshow()` call. The filters are so small that the bilinear interpolation muddles the visualization.

@run2 If you actually want to see the filters as RGB images (as is often done) for the first conv layer you would do something like
```
# assuming W shape is (num_filters, 3, height, width)
for f in W:
    rgb = f.transpose( (1,2,0) ) # to (height, width, channel) order
    # ... normalize to (0,1) if using float or (0, 255) if using uint8 here
    imshow( rgb )
```

This would give you rgb versions of your input filters. Note: if you use opencv to load images they are loaded as bgr, not rgb.

**Comment by fsalmasri** [comment]
@dimatura why it is necessary to normalize the kernel ?  and how to avoid the problem of BGR. I have different plot when I use plt and pixmap .
