### ISSUE TITLE
concat different sized outputs

### ISSUE THREAD

**Issue by skaae** [benanne/Lasagne#107]
I have a network that outputs targets in two different sizes. 

out1 is (batch_size, a) and out2 is (batch_size, b).

I figure i need to concat out1 and out2 for get_params to work properly, but i don't think that the concat layer can handle different size output?

I could possibly get around this by flattening the outputs before concatenation and then reshape them in the cost function.

**Comment by f0k** [comment]
You don't need to concatenate them, you can just use `get_params([out1, out2])` and also use `out1.get_output()` and `out2.get_output()` separately to obtain the two outputs of the networks for your cost function.
Warning: If `out1` and `out2` use the same inputs (either directly or indirectly), and there is some nondeterministic layer (such as a dropout layer) in between, then the two expressions `out1.get_output()` and `out2.get_output()` will contain redundant computations that cannot be merged by Theano -- see #97. We'll fix that soon (the end of #104 already shows a solution).
