### ISSUE TITLE
May be a nolearn issue - but would really appreciate some help here (randomizing Batches in training)

### ISSUE THREAD

**Issue by run2** [benanne/Lasagne#108]
Hi
I posted this on nolearn too, but may be dnouri is away for a while. Any help will be really appreciated as I really need to understand this asap. Please feel free to close this.

The BatchIterator uses a loop as below
       for i in range((n_samples + bs - 1) / bs):

That means - for each epoch, the training progresses through the set of batches in the same sequence.
I wanted to see what happens if I randomize the sequence of batches.
So I added this code

        v = [i for i in range((n_samples + bs - 1) / bs)]
        random.shuffle(v)
        for i in v:
        #for i in range((n_samples + bs - 1) / bs):

This means, each epoch will have the sequence of batches different. It will go through all the images - but in a different sequence.

This change gave me much faster descent and considerably lower validation errors. So I was happy. 
BUT - the prediction on the (same) test set plummeted like hell. From 86% to 33%.

Why ?

Similarly, I trained with the unmodified loop and stored a net. I loaded that net in a separate code, and used it to predict on a test set. Once with the unmodified loop, once with the modified loop. Again the same behavior, massive decrease in the unmodified loop BatchIterator.

For the fact of the matter, I never thought that the decrease can be caused by the BatchIterator during prediction. It was after several hours of playing around that I figured.

So again question - what is happening here ? Why the prediction on same test set is so bad when using my modified loop even though the validation errors are much lower during training ? And what is the BatchIterator being used for while prediction ?

Thanks a lot helping out in advance

**Comment by benanne** [comment]
BatchIterator is indeed part of nolearn, not Lasagne, so you will have to take it up there.

**Comment by dnouri** [comment]
@run2, care to point me at the issue in the nolearn tracker?  I can't seem to find it.  Or maybe add an issue there if you've posted this elsewhere.

**Comment by run2** [comment]
Daniel - just added.
https://github.com/dnouri/nolearn/issues/27

Thanks a ton for looking into this. This is really baffling me.
