### ISSUE TITLE
Create a mailing list

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#109]
We should set up a mailing list (or Google group or whatever). People are starting to post questions and support requests as GitHub issues and that's not really the idea, I think. It would be nicer to keep that separate from the actual development process. I already talked about this briefly with @craffel before. 

We could also consider waiting until we have a release, but I don't really see any good reasons to do that. One of the advantages of having a mailing list already at this stage is that we can more easily communicate potential breaking changes to the users.

What does everyone think? How should we go about it?

**Comment by dnouri** [comment]
Good idea!

**Comment by craffel** [comment]
:+1:

**Comment by benanne** [comment]
so shall I just go ahead and create a google group then?

**Comment by craffel** [comment]
>so shall I just go ahead and create a google group then?

:+1: :+1:

**Comment by benanne** [comment]
Here we go: https://groups.google.com/forum/#!forum/lasagne-users
