### ISSUE TITLE
importing GPU-dependent code when no GPU is available

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#116]
In #114 we briefly talked about the issue of GPU-dependent submodules such as `lasagne.layers.cuda_convnet`, `lasagne.layers.corrmm` and `lasagne.layers.dnn`. Before, these modules were always imported and the GPU-dependent code failed at runtime. In #114 this was changed so the submodules would fail to import into the `lasagne.layers` namespace, which is a bit nicer.

However, if no GPU is available, these submodules simply won't be imported now, with no indication as to why (see https://github.com/benanne/Lasagne/blob/master/lasagne/layers/__init__.py#L11). That is not ideal, it would be nice to be able to communicate this to the user.

I thought about the possibility of raising warnings, but that will just get annoying for people who don't want to use these modules to begin with. Replacing all unavailable classes with dummy classes that raise errors on usage is not a feasible solution either (very involved and not really better than how things were before).

Another solution is to never import the GPU-dependent modules into the `lasagne.layers` namespace automatically to begin with, and require that they are imported explicitly. (This was originally the case for the `cuda_convnet` submodule.) This is probably the cleanest solution for now, but it would mean that some `Layer` subclasses are in `lasagne.layers` while others aren't, which is a bit inconsistent.

Is there anything else we can do to make GPU-dependent code fail early when no GPU is available, while still clearly communicating the cause of the failure?

**Comment by dnouri** [comment]
On 01/28/2015 10:55 AM, Sander Dieleman wrote:
> Another solution is to never import the GPU-dependent modules into the
> |lasagne.layers| namespace automatically to begin with, and require that
> they are imported explicitly. (This was originally the case for the
> |cuda_convnet| submodule.) This is probably the cleanest solution for
> now, but it would mean that some |Layer| subclasses are in
> |lasagne.layers| while others aren't, which is a bit inconsistent.

I like this one.  If there's consensus, I'll do it as part of #114.

**Comment by benanne** [comment]
I already merged #114 though, was I too enthusiastic? :p

**Comment by dnouri** [comment]
Oh, didn't get that.  Thumbs up for your enthusiasm.  ;-)

**Comment by f0k** [comment]
> Is there anything else we can do to make GPU-dependent code fail early when no GPU is available, while still clearly communicating the cause of the failure?

If it was really just about GPU-dependency, they could be grouped into a `lasagne.layers.gpu` namespace that needs to be imported explicitly to have all the GPU-dependent layers available, similar to how Theano has everything in `theano.sandbox.cuda`. But it's also about cuDNN, and about cuda-convnet, and there may be other dependencies in future... this means we will have to create a namespace in `lasagne.layers` or `lasagne.layers.gpu` for every such dependency. That's a bit unfortunate, but on the other hand it's the same in Theano and it requires users to explicitly think about and state their dependencies (as `import` statements). I find that more important than the convenience of auto-importing "everything that goes".

So +1 for explicit imports, but while we're at it, we could think a bit about how to structure the namespace and files.
1. One submodule per dependency: `lasagne.layers.cudnn`, `lasagne.layers.pylearn2`?
    1. Have `cudnn.py` and `pylearn2.py` with all their layers in one file
    2. Have `cudnn/__init__.py`, `cudnn/conv.py`, `cudnn/pool.py`, etc.
2. A `lasagne.layers.gpu` submodule that groups all gpu-dependent layers, with further submodules

I'd go for 1.1, we can always transparently switch to 1.2 later if some submodule turns too big, similar to how we split up the collection of layers in the first place.
Note that we're free to pick new names for `dnn.py` and `cuda_convnet.py` now if we feel like it.

**Comment by benanne** [comment]
Yeah, I guess there's really no way around it. And explicit is probably better than implicit in this case. So we can just remove the imports of these modules in `lasagne/layers/__init__.py` I guess, and make sure to mention in the docs that they should now be imported explicitly.

I wouldn't rename `cuda_convnet` because there is already a lot of code out there that refers to `lasagne.layers.cuda_convnet`, so that would work just fine with just an additional import.

Maybe `cudnn` is a better name than `dnn`? I don't know, I just went with `dnn` because that's what Theano uses.

**Comment by f0k** [comment]
> I wouldn't rename `cuda_convnet` because there is already a lot of code out there that refers to `lasagne.layers.cuda_convnet`

Ah, okay, I thought there wouldn't because the layers are available directly in `lasagne.layers`. Well, then maybe we should also better leave `dnn` as it is (although I think `cudnn` would have been more suitable both here and in Theano).

**Comment by benanne** [comment]
I agree that `cudnn` is more suitable, but since Theano calls it `dnn` we might as well follow.

I'm not really in favour of renaming `cuda_convnet` to `pylearn2` either, the former is a bit more clear on what the module is actually for. It's the only part of pylearn2 that we depend on and I don't see that changing.

**Comment by f0k** [comment]
> So, shall we remove the imports of these modules in `layers/__init__.py` then?

Yes. I guess you can probably just commit that to `master` right away, there's no need for a PR. Be sure to run the tests, though.

**Comment by benanne** [comment]
it's probably better to make a pull request, the tests need some non-trivial changes (they currently check for the availability of implementations with `hasattr(lasagne.layers, ...)` which leads to all those tests being skipped now.

**Comment by benanne** [comment]
This has been addressed in #123.
