### ISSUE TITLE
Large data that does not fit into memory

### ISSUE THREAD

**Issue by benjaminklein** [benanne/Lasagne#122]
I'm new to Lasagne. In the examples that I saw until now, all the data is loaded into memory. What if the data is too large. How can the library be used to load in each mini-batch a chunk from the disk?

**Comment by run2** [comment]
Did you try reducing your batch_size ?

**Comment by benjaminklein** [comment]
Not sure that I understand.. I'm not talking about the GPU memory.
I'm talking about loading the data into memory before calling the network with fit method.
What if my computer's memory (not the GPU's) is not large enough to load the data before calling fit.

**Comment by benanne** [comment]
Lasagne only generates Theano expressions for now, you have to write the training loop code yourself (or copy it from one of the examples, or use `nolearn.lasagne`). There is a related discussion on the mailing list: https://groups.google.com/forum/#!topic/lasagne-users/6F3gCfgviks

**Comment by craffel** [comment]
Because this has come up multiple times (my labmate asked this question too), I'd suggest we add a short note to the examples stating that we're loading the dataset into shared variables because it's small; for large datasets you'll need to handle online data sampling yourself.

**Comment by benanne** [comment]
Good idea, but we should really start thinking more seriously about adding some training loop code as well (#12). It would be great if we have at least some rudimentary training loop code in the library for the most common use cases when we make the first release.
