### ISSUE TITLE
CPU alternative for those without GPU

### ISSUE THREAD

**Issue by tleeuwenburg** [benanne/Lasagne#128]
My laptop doesn't have a cuda-compliant GPU. It would be very nice if all/most of the classes in the cuda_convnet library had a CPU-based equivalent ordinary layer. I would be happy to help but I'm too green to really DIY the solution at this stage. I realise it's slower, but it means that more people can utilise the code...

Let me know if there's anything I can do to help.

**Comment by benanne** [comment]
I'm not sure I follow - `lasagne.layers.Conv2DLayer` and `lasagne.layers.cuda_convnet.Conv2DCCLayer` are supposed to be functionally equivalent to the extent that this is possible. The same goes for `MaxPool2DLayer` and `MaxPool2DCCLayer`. The former of these layer pairs should be able to run on the CPU just fine (albeit very slowly).

Is there any particular feature you are looking for that is not currently available on the CPU?

**Comment by tleeuwenburg** [comment]
Oh -- it's my fault. I got lost in the libraries. I wanted a MaxPool2DLayer, but went looking inside conv rather than inside pool. I just didn't really grok the structure and thought it was missing, but it was just elsewhere. Thanks!

**Comment by benanne** [comment]
No worries, we need to sort out our docs!
