### ISSUE TITLE
conv1d output dimensions

### ISSUE THREAD

**Issue by skaae** [benanne/Lasagne#137]
Im trying the conv1d layers and the output dimensions seems wrong

```PYTHON
import lasagne
import numpy as np
import theano.tensor as T
import theano


BATCH_SIZE = 16
NFEATURES = 5
SEQLEN = 10
FILTERSIZE = 3
NUMFILTER = 2


input = T.tensor3('input')
#(batch_size, n_features, length).
inshp = (BATCH_SIZE, NFEATURES, SEQLEN)
test_val = np.random.rand(*inshp).astype(theano.config.floatX)


inputlayer = lasagne.layers.InputLayer(shape=inshp)
conv1d = lasagne.layers.Conv1DLayer(
    inputlayer, NUMFILTER, FILTERSIZE, border_mode='same')

print conv1d.get_output_shape()

fun1 = theano.function([input],conv1d.get_output(input))

print fun1(test_val).shape
assert fun1(test_val).shape == inshp
```

Conv1d correctly reports its output shape as `(16, 2, 10)` i.e `(BATCH_SIZE, NUM_FILTER, SEQLEN)`
but the actual output is (16, 2, 7)

I get the following reported / actual outputs with different border modes

 * `valid` (16, 2, 8) / (16, 2, 8)
 * `same`  (16, 2, 10) / (16, 2, 7)
 * `full`  (16, 2, 12) / (16, 2, 8)

**Comment by benanne** [comment]
It looks like the implementation of `lasagne.theano_extensions.conv1d_mc0` does not handle border modes correctly (same for the `mc1` version). It is not being passed to `T.nnet.conv2d`. This should be an easy fix, if you want to do it.

At some point we'll need to add some tests for the code in `theano_extensions`. In the long run I hope Theano will get its own `conv1d` so we can just get rid of it.

**Comment by skaae** [comment]
Yes it look that way, I’ll create pull request

best regards Søren

**Comment by skaae** [comment]
PR 
https://github.com/benanne/Lasagne/pull/139

**Comment by benanne** [comment]
Merged. I'll tag #112 here so we remember to add tests for this module at some point (preferably sooner rather than later).

**Comment by benanne** [comment]
Looks like there's a plan to work on a conv1d op for Theano now :)
https://github.com/Theano/Theano/issues/2505
