### ISSUE TITLE
Two or more inputlayers

### ISSUE THREAD

**Issue by tofigh-** [benanne/Lasagne#140]
Hi all,
First of all great job. I hope to find some time to contribute something to Lasagne. My question is: How can I have two or more separate input layers? Like when I want to have several parallel conv layers all connected to a Dense layer? The difficulty is the last layer where  the objective.get_loss will accept only ONE input if I get it correctly.
Cheers

**Comment by benanne** [comment]
You can pass a dictionary mapping layer instances to Theano expressions:
```
objective.get_loss({l_in1: x1, l_in2: x2 })
```

Alternatively, you can call `get_loss()` without specifying inputs:
```
objective.get_loss()
```

Then you can refer to the inputs as `l_in1.input_var` and 'l_in2.input_var`. These symbolic variables are created automatically and are used when you don't specify an input expression.

For future reference, please post support questions on our mailing list, so we can keep the issue queue for development only :) Thanks!

You can find it here: https://groups.google.com/forum/#!forum/lasagne-users

**Comment by tofigh-** [comment]
Thanks for prompt  answer and sorry for posting in wrong place.

**Comment by benanne** [comment]
No worries, thanks for your understanding!
