### ISSUE TITLE
momentum updates for broadcastable parameters

### ISSUE THREAD

**Issue by takacsg84** [benanne/Lasagne#143]
Currently updates that use momentum don't support the update of broadcastable parameters. In order to do this, very little change is needed.
For example in nesterov_momentum:

```python
mparam_i = theano.shared(np.zeros(param_i.get_value().shape, dtype=theano.config.floatX))
```
can be changed to 
```python
mparam_i = theano.shared(np.zeros(param_i.get_value().shape, dtype=theano.config.floatX),
                                 broadcastable=param_i.broadcastable)
```
This is also needed for #141

**Comment by benanne** [comment]
Good call. I guess this also applies to all other update generation functions that need accumulators. A pull request would be very welcome, if not I'll try to take care of it this weekend.

**Comment by takacsg84** [comment]
Yeah, sure. I`ll do it later today.
