### ISSUE TITLE
How important is it to define the batch_size?

### ISSUE THREAD

**Issue by ebattenberg** [benanne/Lasagne#145]
When I was hacking on @benanne's Galaxy Challenge code on a previous project, I found it useful to reuse the same network with different batch sizes (especially during test time).

When I did that, I don't remember there being any strong reason to define the batch size.  I think there was an older version of conv2D in Theano that used this information for optimization, but I think the currently used GPU routines don't seem to need to know the batch size beforehand.  

I haven't looked into this that deeply for Lasagne, but I was wondering why we need to define the batch size (first dimension of `shape`) for a network.   It would be nice if we could be more flexible if possible.

**Comment by benanne** [comment]
Try specifying `None` and see what happens :) we're trying to support `None` in shapes everywhere where it's possible (but I'm not sure if there are too many tests for this yet). Variable batch sizes are the main reason, but it could probably be useful elsewhere as well.

This once again shows that we really need to spend some time working on our documentation...

**Comment by benanne** [comment]
I will close this, but feel free to open a new issue if you notice anything that's supposed to work with `None` and doesn't.

**Comment by ebattenberg** [comment]
Cool.  Using `None` was what I did in the past, so I'm glad this is the intention with Lasagne.
