### ISSUE TITLE
No documentation text on readthedocs.org

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#148]
readthedocs seems to parse the rst files, but it's not actually including any of the docstrings anymore. I don't know what happened. From the build log it looks like it fails to install numpy, but I don't know why this started failing all of a sudden: https://readthedocs.org/builds/lasagne/2360170/

Anybody have any idea how to fix this?

**Comment by dnouri** [comment]
So here's an issue that's probably related:
https://github.com/rtfd/readthedocs.org/issues/217

It looks like numpy is installed via apt-get on the build server.  We need `--system-site-packages` to be able to use it.  There should be a setting in RTD.

**Comment by benanne** [comment]
It looks like "use virtualenv" is disabled in the advanced settings though (it is disabled by default). `--system-site-packages` is a virtualenv option, isn't it?

**Comment by benanne** [comment]
Actually, I also found an option "Give the virtual environment access to the global site-packages dir." there, that was also disabled. I've just enabled it. The "use virtualenv" one is still disabled though. But maybe it does that by default now.

**Comment by dnouri** [comment]
Hmm, that's confusing.

**Comment by benanne** [comment]
Ok, checking that box seems to have fixed it, the documentation text is back :)
