### ISSUE TITLE
error in output shape calculation for strided Conv2DLayer with border_mode='full'

### ISSUE THREAD

**Issue by ebenolson** [benanne/Lasagne#154]
Simple example:

        l_in = lasagne.layers.InputLayer(
            shape=(1, 1, 10, 10),
        )

        l_conv = lasagne.layers.Conv2DLayer(
            l_in,
            num_filters=1,
            filter_size=(3, 3),
            strides=(2,2),
            border_mode='full',
        )

`l_conv.get_output_shape()` gives (1, 1, 5, 5)
But `l_conv.get_output(x).shape` yields (1, 1, 6, 6)

**Comment by benanne** [comment]
Weird, shouldn't it be `(image_size + filter_size) // stride - 1`? I guess not. I suppose the mistake in my thinking could be in the integer division. Should we round up there instead?

Which convolution backend is being used for Theano (I'm guessing cudnn)? Does this problem occur for other convolution backends as well?

**Comment by benanne** [comment]
It looks like Theano's CPU convolution implemention uses the formula `(image_size + filter_size + stride - 2) // stride`. I don't get the logic behind this at all, but I suppose we should simply use the same formula.

**Comment by ebenolson** [comment]
I think I've seen a similar problem for the cuda-convnet backend as well.

**Comment by benanne** [comment]
Yes, the mistake will be in all implementations because that's the formula I've been using. It should be correct when the filters tile the input nicely, but I guess it's wrong when they don't. I never use full convolutions, or shapes that don't tile nicely, which would explain why I haven't noticed it before. Should be a simple fix. Feel free to send a pull request, else I'll try to find some time for it tomorrow.

**Comment by ebenolson** [comment]
yeah, I just came across it while trying to translate a caffe model. 
I'll try to put together a fix, thanks for pointing me to the answer.

**Comment by f0k** [comment]
> EDIT: actually I do understand, the explanation is in the comments above it.

Yep, when I write funny code, I make sure to explain it :) For Lasagne I'd propose to use the less funny version, we don't have to deal with symbolic shapes in `Layer.get_output_shape_for()` so we can use `np.ceil`.
