### ISSUE TITLE
Is it possible to save model in the middle of training and resume with the saved training model

### ISSUE THREAD

**Issue by YunshuLiu** [benanne/Lasagne#159]
I am wondering if there is ways to load model and continue training?
Usually I would like to try out a fixed learning rate and when the loss stop improving,
I stop the training and used the saved model to continue training with a much smaller learning rate.

**Comment by senbon** [comment]
While no official read/write interface exist you could have a look at #7 for how you could utilise ```lasagne.layers.get_all_params(model)```.

I use the same method in my setup: https://gist.github.com/senbon/70adf5410950c0dc882b
You can continue the training as you normally would after having read the stored parameters.

**Comment by YunshuLiu** [comment]
I tried directly using your code like this
    for setting in SPECIALIST_SETTINGS:
        cols = setting['columns']
        #X, y = load2d(cols=cols)
        X, y = load2d()
        model = clone(net)
        if 'kwargs' in setting:
            vars(model).update(setting['kwargs'])
        model.fit(X, y)
        specialists[cols] = model
        store_model_data(model,'first_stage_model')

it raise a error, I guess I still don't know how to use it...
  File "run_analysis.py", line 136, in fit
    store_model_data(model,'first_stage_model')
  File "/home/sky/projects/helper-dsbowl/lasagne/params.py", line 20, in store_model_data
    params = lasagne.layers.get_all_params(model)
  File "/home/sky/softwares/anaconda/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/helper.py", line 96, in get_all_params
    params = sum([l.get_params() for l in layers], [])
TypeError: can only concatenate list (not "_dict") to list

**Comment by dnouri** [comment]
@YunshuLiu It looks like you're using nolearn.lasagne.  You should be able to do:
```python
model.save_weights_to('first_stage_model')  # saves to a file
# later on:
model.load_weights_from('first_stage_model')
```

**Comment by YunshuLiu** [comment]
Thanks for your help guys, really appreciate it :)

**Comment by krikru** [comment]
If it would have been possible (but I don't think it currently is in Lasagne), you should also save the internal state of the optimizer so you can restore that as well when you continue the training, as it contains a lot of information that is of value for the training. If you use the `nesterov_momentum` optimizer for example, you should ideally also save the `velocity` vector in the function `apply_nesterov_momentum` so you can continue the training without having to reset the velocity to zero when you start training again.

Resetting the velocity to zero means that you loose "kinetic energy", which if you are unlucky may make you get stuck in a local minimum for which you need a certain amount of "energy" in order to escape.

**Comment by f0k** [comment]
> If it would have been possible (but I don't think it currently is in Lasagne), you should also save the internal state of the optimizer so you can restore that as well when you continue the training

Yes, this is indeed important. It's easily possible by saving the values of all keys of the update dictionary:
```python
# for saving:
values1 = [p.get_value() for p in updates.keys()]
values2 = lasagne.layers.get_all_param_values(network, trainable=False)
# for restoring:
for p, value in zip(updates.keys(), values1):
    p.set_value(value)
lasagne.layers.set_all_param_values(network, values2, trainable=False)
```
Note that the update dictionary does not include non-trainable weights (e.g., batch normalization running averages), so they need to be stored and restored separately.

**Comment by edoardogiacomello** [comment]
I tried this last solution, while the parameters seem to be loaded correctly, when I resume the training process my loss seems to start from scratch. Am I missing something theoretical or there could be another reason?
