### ISSUE TITLE
Saving and loading a model

### ISSUE THREAD

**Issue by julj** [benanne/Lasagne#161]
I'm training a model and saving the weights using `model.save_weights_to`, as described in https://github.com/benanne/Lasagne/issues/159.

Now in a different session, I create an instance of NeuralNet with the same parameters as the one used for the training and load the saved weights using `model.load_weights_from`. When I try to run a prediction (`y_pred = net.predict(sample)[0]`) I get:

`AttributeError: 'NeuralNet' object has no attribute 'predict_iter_'`

What's the correct method for saving and loading a trained model? Is there any way to save/load the network parameters too (the topology)?

**Comment by ebenolson** [comment]
See https://github.com/dnouri/nolearn/issues/58

**Comment by benanne** [comment]
The GitHub issues are only for development, please use the mailing list for support: https://groups.google.com/forum/#!forum/lasagne-users

In this case though you seem to have an issue with nolearn, not with lasagne, so you should direct your question there instead. Thanks for your cooperation!
