### ISSUE TITLE
Crash with optimizer_including=conv_meta

### ISSUE THREAD

**Issue by aloisg** [benanne/Lasagne#162]
With the flag optimizer_including=conv_meta, with some CNN code based on Lasagne and when i put a lot of filters per layer, i got the error below. I'm not out of memory on my GPU RAM (only 30%).

This error got away when lowering the number of filters, or when removing the flag optimizer_including=conv_meta. This may not be related to Lasagne, but i didn't know where to post.

I have a full page of errors, ask me if needed.

... getting the finetuning function
Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xbc5000000 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
device_free: cudaFree() returned an error, but there is already an Python error set. This happen during the clean up when there is a first error and the CUDA driver is in a so bad state that it don't work anymore. We keep the previous error set to help debugging it.CudaNdarray_uninit: error freeing self->devdata. (self=0x7fca69ad6c30, self->devata=0xbc5000000)
Error when trying to find the memory information on the GPU: an illegal memory access was encountered
Error allocating 30515200 bytes of device memory (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xbc3280000 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
CudaNdarray_uninit: error freeing self->devdata. (self=0x7fca69ad6df0, self->devata=0xbc3280000)
Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xbbf7a0000 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
device_free: cudaFree() returned an error, but there is already an Python error set. This happen during the clean up when there is a first error and the CUDA driver is in a so bad state that it don't work anymore. We keep the previous error set to help debugging it.CudaNdarray_uninit: error freeing self->devdata. (self=0x7fca69ad6bb0, self->devata=0xbbf7a0000)
Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xb047c9800 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
device_free: cudaFree() returned an error, but there is already an Python error set. This happen during the clean up when there is a first error and the CUDA driver is in a so bad state that it don't work anymore. We keep the previous error set to help debugging it.CudaNdarray_uninit: error freeing dev_structure memory 0xb047c9800 (self=0x7fca69ad6bb0)
Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xbbda40000 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
device_free: cudaFree() returned an error, but there is already an Python error set. This happen during the clean up when there is a first error and the CUDA driver is in a so bad state that it don't work anymore. We keep the previous error set to help debugging it.CudaNdarray_uninit: error freeing self->devdata. (self=0x7fca6a1aef70, self->devata=0xbbda40000)
ERROR (theano.gof.opt): Optimization failure due to: LocalOptGroup(<theano.sandbox.cuda.opt.ConvMetaOptimizer object at 0x7fca83202990>,local_conv_dnn,local_conv_gemm)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1493, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 991, in transform
    repl = opt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 881, in transform
    for opt in self.optimizers:
MemoryError: error freeing device pointer 0xbc3280000 (an illegal memory access was encountered)

**Comment by benanne** [comment]
This would be more appropriate on the Theano mailing list, I think :) But anyway, are you using cudnn? Which version? Try upgrading to the latest release candidate of R2 if you haven't (R2 RC3).

**Comment by aloisg** [comment]
I don't know, i'm simply using Conv2DLayer. How can i check this ?

**Comment by craffel** [comment]
I've been running into this recently too, I'm not sure what causes it.
There's a theano-users thread about it here
https://groups.google.com/forum/#!topic/theano-users/Pu4YKlZKwm4
(I'm using cuda 6.5, cudnn)

∿

**Comment by f0k** [comment]
> I don't know, i'm simply using Conv2DLayer. How can i check this ?

If you don't know, then you're not using cuDNN (this needs to be installed explicitly). For the sake of completeness, you can check it with `theano.sandbox.cuda.dnn.dnn_available()`.

With respect to your error, I don't think it's directly caused by the meta-optimizer (fingers crossed). Reading the thread linked by @craffel, it seems that something somewhere writes out of bounds. This could be caught with `cuda-memcheck`. Can you try running your code with that and report results in [that theano-users thread](https://groups.google.com/forum/#!topic/theano-users/Pu4YKlZKwm4)?

**Comment by aloisg** [comment]
Okay, so i'm not using cuDNN. Should i ? Is there any speed improvement ?

I'll post my report on the thread you mentioned. Thanks !

**Comment by f0k** [comment]
> Okay, so i'm not using cuDNN. Should i ? Is there any speed improvement ?

Usually yes. You can get it [from NVIDIA](https://developer.nvidia.com/cuDNN) after signing up as a "CUDA Registered Developer", and install it as described [in the Theano docs](http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html). You will need CUDA 6.5 along with the necessary driver and a GPU of Compute Capability 3.0 or higher. Check the output of `theano.sandbox.cuda.device_properties(0)`, the `major` and `minor` form the Compute Capability version of your GPU (run the same with `1`, `2` etc if you have multiple different GPUs you want to check).

**Comment by aloisg** [comment]
Okay thanks, i just installed it ;)
I think this issue can be closed !
