### ISSUE TITLE
Conv2DLayer gives the wrong (?) shape when mode='same'

### ISSUE THREAD

**Issue by craffel** [benanne/Lasagne#166]
I ran across this when showing @bmcfee some lasagne stuff.  Basically, when a Conv2DLayer has `mode='same'` and you pass it an input where the second-to-last (or last, I think, but I'm not testing that here) dimension is different than expected, it gives you an output whose shape is what it had expected.  An example is probably easier to understand:

```Python
import numpy as np
import theano
import lasagne
import lasagne.layers.dnn
import lasagne.layers.cuda_convnet
import itertools

# Create network, starting with input layer
l_in = lasagne.layers.InputLayer(shape=(None, 16, 100, 20))
x_same = np.random.randn(1, 16, 100, 20).astype(theano.config.floatX)
x_diff = np.random.randn(1, 16, 200, 20).astype(theano.config.floatX)

for layer, mode in itertools.product([lasagne.layers.Conv2DLayer,
                                      lasagne.layers.cuda_convnet.Conv2DCCLayer,
                                      lasagne.layers.dnn.Conv2DDNNLayer],
                                     ['valid', 'full', 'same']):
    l_1 = layer(l_in, num_filters=16, filter_size=(5, 5), border_mode=mode)
    out = theano.function([l_in.input_var], l_1.get_output())
    for x, shape in zip([x_same, x_diff], ['same', 'diff']):
        print "{}, {}, {}, {}".format(layer, mode, shape, out(x).shape)
```

yields

```
<class 'lasagne.layers.conv.Conv2DLayer'>, valid, same, (1, 16, 96, 16)
<class 'lasagne.layers.conv.Conv2DLayer'>, valid, diff, (1, 16, 196, 16)
<class 'lasagne.layers.conv.Conv2DLayer'>, full, same, (1, 16, 104, 24)
<class 'lasagne.layers.conv.Conv2DLayer'>, full, diff, (1, 16, 204, 24)
<class 'lasagne.layers.conv.Conv2DLayer'>, same, same, (1, 16, 100, 20)
<class 'lasagne.layers.conv.Conv2DLayer'>, same, diff, (1, 16, 100, 20)
<class 'lasagne.layers.cuda_convnet.Conv2DCCLayer'>, valid, same, (1, 16, 96, 16)
<class 'lasagne.layers.cuda_convnet.Conv2DCCLayer'>, valid, diff, (1, 16, 196, 16)
<class 'lasagne.layers.cuda_convnet.Conv2DCCLayer'>, full, same, (1, 16, 104, 24)
<class 'lasagne.layers.cuda_convnet.Conv2DCCLayer'>, full, diff, (1, 16, 204, 24)
<class 'lasagne.layers.cuda_convnet.Conv2DCCLayer'>, same, same, (1, 16, 100, 20)
<class 'lasagne.layers.cuda_convnet.Conv2DCCLayer'>, same, diff, (1, 16, 200, 20)
<class 'lasagne.layers.dnn.Conv2DDNNLayer'>, valid, same, (1, 16, 96, 16)
<class 'lasagne.layers.dnn.Conv2DDNNLayer'>, valid, diff, (1, 16, 196, 16)
<class 'lasagne.layers.dnn.Conv2DDNNLayer'>, full, same, (1, 16, 104, 24)
<class 'lasagne.layers.dnn.Conv2DDNNLayer'>, full, diff, (1, 16, 204, 24)
<class 'lasagne.layers.dnn.Conv2DDNNLayer'>, same, same, (1, 16, 100, 20)
<class 'lasagne.layers.dnn.Conv2DDNNLayer'>, same, diff, (1, 16, 200, 20)
```

Or, in other words, every border mode/layer works as I would expect except for `Conv2DLayer` with `border='same'`.  I think this is due to this line:
https://github.com/benanne/Lasagne/blob/master/lasagne/layers/conv.py#L179
I'm not comfortable enough with the conv code to try to change this myself!

**Comment by ebenolson** [comment]
This can be fixed by changing `self.input_shape` to `input.shape` in line 179, but it seems to me that an error ought to be raised somewhere if an input is applied with a shape that doesn't match what's expected (and those dimensions aren't `None`).

**Comment by bmcfee** [comment]
> This can be fixed by changing self.input_shape to input.shape in line 179, but it seems to me that an error ought to be raised somewhere if an input is applied with a shape that doesn't match what's expected (and those dimensions aren't None).

That sounds sensible to me.  However, `None`-dimensions cause all kinds of exceptions in conv layers for me.  This, I think stems from not checking for `None` in the shape getters, eg from Conv2DLayer:
```python
            output_rows = input_shape[2] // self.strides[0]
            output_columns = input_shape[3] // self.strides[1]
```
I tried to add checks and propagate `None`s in a local branch, but it all blew up in my face.  (PEBKAC most likely, but maybe someone who actually knows what they're doing should take a look...)

**Comment by f0k** [comment]
That's all a bit tricky.

> changing `self.input_shape` to `input.shape` in line 179

This would be a good solution, I wouldn't expect any performance benefit from using the non-symbolic shape here. The same change will probably have to be done for the Conv1D and Conv3D case.

> an error ought to be raised somewhere if an input is applied with a shape that doesn't match what's expected

Such an error will be raised by Theano whenever that poses a problem. There is no way for us to raise an error here because we're only constructing the graph and don't know what inputs the compiled function will be called with, and there's also no need for us to raise an error if Theano is fine with it anyway. (We could enforce the shape by adding `input.reshape(self.input_shape)` or per-dimension assert ops, but there's no benefit to it.)

> However, `None`-dimensions cause all kinds of exceptions in conv layers for me.

I guess we will generally have to go through the code and check for correct `None`-handling (also adding missing tests). Most layers assume that only the batch dimension can be `None`. For some layers this makes sense (e.g., the `DenseLayer` cannot deal with a different number of features than it was created for), but for others some more flexibility would be nice (e.g., the convolutions should be able to deal with anything that has the correct number of input channels).

Note that #156 refactors the shape computation a bit, any changes (such as `None` propagation) should be on top of that.

**Comment by ebenolson** [comment]
> There is no way for us to raise an error here because we're only constructing the graph and don't know what inputs the compiled function will be called with, and there's also no need for us to raise an error if Theano is fine with it anyway. (We could enforce the shape by adding input.reshape(self.input_shape) or per-dimension assert ops, but there's no benefit to it.)

Good point, but I still think it would be beneficial to force users to explicitly declare `None` for dimensions that they want to be variable, and give a more informative error message otherwise. It's pretty unintuitive to me that it works at all otherwise, and I think it could lead to confusion.

For example, changing line 179 will let it run, but the convolution will still be optimized for the original input shape, which I'd imagine might be slower for some other shapes than if no `image_shape` was passed to `nnet.conv2d` at all.

> Note that #156 refactors the shape computation a bit, any changes (such as None propagation) should be on top of that.

This should be pretty simple with the new helper function for shape calculation, but I think a couple of the other conv layers need to be updated to use it.

**Comment by craffel** [comment]
> For some layers this makes sense (e.g., the DenseLayer cannot deal with a different number of features than it was created for), but for others some more flexibility would be nice (e.g., the convolutions should be able to deal with anything that has the correct number of input channels).

Yes please.

> Good point, but I still think it would be beneficial to force users to explicitly declare None for dimensions that they want to be variable, and give a more informative error message otherwise.

Agreed that we should make it so that `None` is allowed for any dimensions for any layers which it makes sense (convolutional, recurrent, etc).

> For example, changing line 179 will let it run, but the convolution will still be optimized for the original input shape, which I'd imagine might be slower for some other shapes than if no image_shape was passed to nnet.conv2d at all.

Can you explain this optimization? I didn't realize this was a thing.

**Comment by benanne** [comment]
afaik shape-based optimization only happens with the legacy convolution implementation. For any of the current implementations (GpuCorrMM, cudnn, fft etc.) it shouldn't make a difference in performance. Maybe for the meta-optimizer it might :)

**Comment by ebenolson** [comment]
> Can you explain this optimization? I didn't realize this was a thing. 

In the [Theano source for conv2d](https://github.com/Theano/Theano/blob/7dc5cf5260a16a8fd9fbdc4f217818ff6cf66379/theano/tensor/nnet/conv.py) it mentions that the `image_shape` parameter is used optimize loop unrolling. 

I just noticed this while looking at the source, and I don't know how much effect it might have. I think it illustrates how not being explicit about which dimensions are variable could lead to a mismatch between user and developer assumptions though.

**Comment by f0k** [comment]
> For example, changing line 179 will let it run, but the convolution will still be optimized for the original input shape, which I'd imagine might be slower for some other shapes than if no `image_shape` was passed to `nnet.conv2d` at all.

If Theano doesn't throw a runtime error when faced with a different input shape, then the convolution implementation that it ended up using isn't optimized for a particular shape. The implementation might have been selected depending on the shape you gave, though.

> afaik shape-based optimization only happens with the legacy convolution implementation. For any of the current implementations (GpuCorrMM, cudnn, fft etc.) it shouldn't make a difference in performance. Maybe for the meta-optimizer it might :)

It's true that the legacy convolution is the only one that can be compiled to only accept the shape you gave at compile time. But for the other convolutions, the chosen algorithm may be dependent on the compile time shape information, even on the batch size (see the ["swapping trick"](http://benanne.github.io/2014/12/09/theano-metaopt.html#the-swapping-trick)). And the meta-optimizer needs fully specified compile-time shapes to be able to run at all.

Anyway, the compiled function may still be able to run with different shapes than given at compile time, and I don't think we should try to prevent that (apart from the fact that it's hard to do so, see my previous comment).

>> Note that #156 refactors the shape computation a bit, any changes (such as None propagation) should be on top of that.

> This should be pretty simple with the new helper function for shape calculation, but I think a couple of the other conv layers need to be updated to use it.

That's the way to go!

**Comment by bmcfee** [comment]
> Good point, but I still think it would be beneficial to force users to explicitly declare None for dimensions that they want to be variable, and give a more informative error message otherwise. It's pretty unintuitive to me that it works at all otherwise, and I think it could lead to confusion.

:+1:  Definitely does lead to conclusion.

For the record, I get different outputs from Colin's example above.  (I'm on b3f291383ceeb4b1fa64a230607455a2f1bb687b ).

```
<class 'lasagne.layers.conv.Conv2DLayer'>, valid, same, (1, 16, 96, 16)
<class 'lasagne.layers.conv.Conv2DLayer'>, valid, diff, (1, 16, 96, 16)
<class 'lasagne.layers.conv.Conv2DLayer'>, full, same, (1, 16, 104, 24)
<class 'lasagne.layers.conv.Conv2DLayer'>, full, diff, (1, 16, 104, 24)
<class 'lasagne.layers.conv.Conv2DLayer'>, same, same, (1, 16, 100, 20)
<class 'lasagne.layers.conv.Conv2DLayer'>, same, diff, (1, 16, 100, 20)
```

So it's not just `border_mode='same'` that causes trouble.

**Comment by craffel** [comment]
I get the output posted above on my laptop (CPU) and my GPU box.  @bmcfee, might be worth trying with Theano at the latest commit as opposed to the latest stable release (that's the only other place I can think of something being different)

**Comment by bmcfee** [comment]
Ah, good call.  I'm on theano 647921d7d26f4a848f023d5c7ef6329f4dfb5563 (the rev listed in your tutorial, as i recall).

**Comment by ebenolson** [comment]
>>> Note that #156 refactors the shape computation a bit, any changes (such as None propagation) should be on top of that.

>>This should be pretty simple with the new helper function for shape calculation, but I think a couple of the other conv layers need to be updated to use it.

>That's the way to go!

Ok, I can try adding `None` propagation. I think I'll create a new PR for it though, #156 has a lot going on already.

**Comment by f0k** [comment]
> Ok, I can try adding `None` propagation.

That would be nice! It's basically just a check in the beginning (`if ... is None or ... is None: return None`), the main work is to make all convolution implementations use your helper function and test that `None` propagation works.

> I think I'll create a new PR for it though

Definitely. #156 should be merged as-is when Sander gets around to it (he's still abroad, I think).

> I get the output posted above on my laptop (CPU) and my GPU box.

Note that results may also depend on whether cuDNN is available or not.

**Comment by craffel** [comment]
> Note that results may also depend on whether cuDNN is available or not.

My laptop has no nVidia GPU (so no cuda or cuDNN); my GPU box has cuda/cuDNN, both give the results posted above.

**Comment by f0k** [comment]
Possibly Brian doesn't have cuDNN and falls back to the gemm-based convolution, that would explain the difference. I'm not sure how I treated shapes there.

**Comment by bmcfee** [comment]
I also don't have cudnn/cuda on this machine.  (That was the whole start of this thread off-line, in which I whine like a baby about not having a gpu to develop on. :))

**Comment by craffel** [comment]
> Possibly Brian doesn't have cuDNN and falls back to the gemm-based convolution, that would explain the difference. I'm not sure how I treated shapes there. 

Sorry, just to be absolutely clear, on both of my systems (one without cuda/cuDNN, and one with both), I get the same output (posted at the top).  Brian gets different output on his (no cuda, no cuDNN) machine than on both of my machines.

**Comment by f0k** [comment]
Yep, got it now. So then the two CPU versions should have been the same (as there's only one CPU convolution in Theano), and I'm with you that the next best explanation is that Brian uses a different Theano version. Anyway, we cannot really do anything about this in Lasagne (except for the fix of line 179 that will affect "same" convolution only). The best we can do (and should do) is to clearly document the correct way of specifying shapes.

**Comment by bmcfee** [comment]
I get the same output as I reported before when using theano 0.7rc2.

Full dump [here](http://nbviewer.ipython.org/gist/bmcfee/46de6a5e1d70618db957).

**Comment by ebenolson** [comment]
I see the same problem in CPU mode. 

However, if I remove line 169 (`image_shape=input_shape,`), I get the correct output shape.

**Comment by f0k** [comment]
> I see the same problem in CPU mode.
> However, if I remove line 169 (image_shape=input_shape,), I get the correct output shape.

I'd say this is a bug in Theano then. It should either give correct output or bail out, not silently accept input of a different shape than expected and return output of a wrong shape for that. Does one of you feel like reporting it upstream? (Along with a minimal working example that directly calls `theano.nnet.conv2d()` instead of Lasagne's layer.)

**Comment by ebenolson** [comment]
I opened an issue upstream. https://github.com/Theano/Theano/issues/2620

**Comment by craffel** [comment]
Using 
```Python
l_in = lasagne.layers.InputLayer(shape=(None, 16, None, 20))
```
I get
```
<class 'lasagne.layers.conv.Conv2DLayer'>, same, same, (1, 16, 100, 20)
<class 'lasagne.layers.conv.Conv2DLayer'>, same, diff, (1, 16, 200, 20)
```
which is what I would hope for, thanks!  However, a MaxPool2DLayer will still die when there's a `None` outside of the first dimension:
```Python
In [1]: import lasagne
Using gpu device 0: GeForce GTX 780 Ti

In [2]: l_in = lasagne.layers.InputLayer(shape=(None, 16, None, 20))

In [3]: l_1 = lasagne.layers.Conv2DLayer(l_in, num_filters=16, filter_size=(5, 5))

In [4]: l_2 = lasagne.layers.MaxPool2DLayer(l_1, (2, 2))

In [5]: l_2.get_output_shape()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-794da6445de8> in <module>()
----> 1 l_2.get_output_shape()

base.pyc in get_output_shape(self)
     90             keep this unchanged and just override `get_output_shape_for()`.
     91         """
---> 92         return self.get_output_shape_for(self.input_shape)
     93
     94     def get_output(self, input=None, *args, **kwargs):

pool.pyc in get_output_shape_for(self, input_shape)
     30                                            self.ds[1]))
     31         else:
---> 32             output_shape[2] = int(np.ceil(float(output_shape[2]) /
     33                                           self.ds[0]))
     34             output_shape[3] = int(np.ceil(float(output_shape[3]) /

TypeError: float() argument must be a string or a number
```
I think pooling layers should also support `None`s, can we support this?

**Comment by benanne** [comment]
Yes we can! It's just a question of setting the output shape dimension to `None` is the corresponding input shape dimension is `None`. Maybe make a separate issue for this so we don't lose track of it. Or better yet, a PR ;)

**Comment by bmcfee** [comment]
> Or better yet, a PR ;)

I already started patching this locally, I'll try to pr later today
