### ISSUE TITLE
MaxPool1DLayer Implementation? 

### ISSUE THREAD

**Issue by msevrens** [benanne/Lasagne#184]
It looks like MaxPool1DLayer is unimplemented. How could I get around that? I'm not sure how to implement it within the context of the library.

**Comment by benanne** [comment]
Good catch, we'll need to add that. There are a number of ways to do it, one way is to reshape the input, basically something like this:

```
input = T.tensor3() # (batch_size, num_channels, length)
pool_size = ...
input_r = input.reshape((input.shape[0], input.shape[1], input.shape[2] // pool_size, pool_size))
output = input_r.max(axis=3)
```

For this to work correctly in all cases you will need to truncate input or pad it, or just ensure that its length is always a multiple of the pool size.

Alternatively you can use the existing 2D pooling primitives in Theano and just reshape the input to be 4D, and then set the corresponding pool size to 1. In combination with cudnn this might actually be the fastest way to do it. i.e. something like:

```
input = input = T.tensor3() # (batch_size, num_channels, length)
pool_size = ...
input_r = input.shape_padright(1) # this is the same as input.reshape((batch_size, num_channels, length, 1))
output_r = theano.tensor.signal.downsample.max_pool_2d(input_r, ds=(pool_size, 1))
output = output_r[..., 0] # chop off the dummy axis we added
```

We need this in the library so I might spend some time on it in the next few days, but PRs are always welcome!

**Comment by benanne** [comment]
I've created a PR: #185

**Comment by msevrens** [comment]
Wow! That is a damn incredible turnaround time! Thank you!

**Comment by benanne** [comment]
I'm procrastinating so I might as well make myself useful :) might take a day or two before it gets merged though.

**Comment by benanne** [comment]
Done! This was added in #185.
