### ISSUE TITLE
Can we get the exact activation value of some neuron from Lasagne?

### ISSUE THREAD

**Issue by paipai880429** [benanne/Lasagne#189]
@benanne 
Hi benanne, we know that Lasagne is based on theano and is intended to provide a more convenient way to build up a ConvNet model. I would like to know if we can get the exact activation value of some neuron(say, the second convolutional layer, the 100th neuron) from Lasagne? Thank you .

**Comment by benanne** [comment]
Yes:

```
second_convolutional_layer.get_output()[:, 100]
```

That will give you the Theano expression for it, you will just have to compile that into a function.
Be careful though, if the network features non-deterministic layers (i.e. dropout) there may be issues with this approach, which we are currently addressing in #104.and #182.

Please post support questions like this one on our mailing list in the future: https://groups.google.com/forum/#!forum/lasagne-users
We would like to keep the GitHub issue queue restricted to development and bug reports only. Thanks for your cooperation!

**Comment by paipai880429** [comment]
@benanne Thank you for you prompt reply, though I am still not clear. Then I will new a question in google groups. See you there.

**Comment by paipai880429** [comment]
https://groups.google.com/forum/#!topic/lasagne-users/UESBpEc6UME
