### ISSUE TITLE
"linear" is in "nonlinearities"

### ISSUE THREAD

**Issue by MartinThoma** [benanne/Lasagne#198]
The module `nonlinearities` should be renamed to `activations` or `activation_functions` as there are two linear activation functions in it (linear and identity). Also, I think it is more logical to call it `activation_functions` than `nonlinearities`.

**Comment by benanne** [comment]
Honestly I don't think it matters that much. And changing it now is mainly going to annoy people because they have to modify their code. But if enough people feel that this name should be changed, I guess now is the time to do it.

**Comment by MartinThoma** [comment]
Well, I would make it like this:

1. Rename `nonlinearities.py` to `activation_functions.py`
2. Create `nonlinearities.py` with the content content:

```python
import warnings
msg = "This module was replaced by the module `activation_functions`."
warnings.warn(msg, category=DeprecationWarning)
from activation_functions import *
```

This should make all existing code work, but people should get the warning if they use the old module.

**Comment by benanne** [comment]
We can only really do that as long as the first release hasn't happened, it doesn't make sense to carry around baggage already in the first release. Also, the argument on `Layer` constructors is called `nonlinearity`, so this would also have to be changed and that would break almost everyone's code.

Hence why I said if we're going to change it, now is the time. But personally I don't think we should. I welcome everyone to share their preference though, if there is enough support for it we should do it.

**Comment by f0k** [comment]
Sure, but that would be annoying enough. Also we'd have to change the keyword argument on most layers as well, not just the module name. I think `activation_function` is too long, and `activation` is not specific enough. I'd stay with `nonlinearity` and live with the fact that the only useful non-nonlinear function is in there as well.

**Comment by ebenolson** [comment]
I can see the logic in changing it, but I'd prefer the less verbose `activations`.

**Comment by ebenolson** [comment]
Yeah, changing the kwarg I think would be too much, that's a good reason to leave it as is. 

Although it will be a bit funny when the default `nonlinearity` is linear after https://github.com/benanne/Lasagne/issues/138 is fixed.

**Comment by MartinThoma** [comment]
According to `grep -rni "nonlinearities" * | wc -l` I would have to change it in 64 places. It's a bit of work, but I would do it.

I don't see the problem with kwargs. Could you please explain it?

**Comment by f0k** [comment]
> I don't see the problem with kwargs.

Do a grep for `nonlinearity` as well and you'll understand.

> Although it will be a bit funny when the default `nonlinearity` is linear

I think with `nonlinearity=None` it would sound quite plausible.

**Comment by benanne** [comment]
@eben: `nonlinearity=None` is equivalent, so that's not really an issue :)

**Comment by benanne** [comment]
I think the consensus is to keep this as it is for now, but feel free to reopen this if any other compelling arguments in favor of  changing it come up.
