### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#21]
What is everyone's stance on enforcing [PEP8](http://legacy.python.org/dev/peps/pep-0008/)? Personally I think it's good to enforce some coding standards, but the 80 character line length limit really annoys me sometimes. @avdnoord feels the same way. Maybe there are good arguments in favor of it though?

Are there any good tools (perhaps with GitHub integration) that make enforcing this easier?

**Comment by ebattenberg** [comment]
I think python mode in vim is really handy.    And +1 for sticking with PEP8.

**Comment by ebattenberg** [comment]
And while python mode in vim shows you all the violations from installed checkers in-line, you can always run those programs separately to get the feedback.  Those that are supported include:

https://pypi.python.org/pypi/pep8
https://pypi.python.org/pypi/pyflakes
https://pypi.python.org/pypi/pylint
https://pypi.python.org/pypi/mccabe
https://pypi.python.org/pypi/pep257

**Comment by craffel** [comment]
Sander, in #149, writes

>  But the PEP8 issue (#21) never came to a conclusion - we should take care of that first.

I think the conclusion reached here is "Some people think 80 characters is too short but we should follow PEP-8 anyways".  As I mentioned, it's very easy to force yourself to follow PEP-8 using a plug-in in your favorite editor, and it's much easier to point to a (universally accepted) style guide then to make your own up when you are soliciting pull requests.

**Comment by benanne** [comment]
Let's do it. As I said before I can live with it if necessary. I'll adapt :) If anyone has any other concerns, please comment as soon as possible.

We should probably do a sweep of the entire codebase (preferably in a limited number of commits) to ensure that all of the current code follows PEP8. That will make it much easier to enforce for future pull requests.

**Comment by craffel** [comment]
> We should probably do a sweep of the entire codebase (preferably in a limited number of commits) to ensure that all of the current code follows PEP8.

I can do this.  I usually advocate for one commit per file - makes it easier to roll back changes if something breaks, although if you'd prefer a single commit that's fine too.

**Comment by benanne** [comment]
Good point, I guess one commit per file is best.

**Comment by ebattenberg** [comment]
I prefer exactly two commits per file.  ;)

I just realized that I've been using `'''` in my docstrings all along while PEP 257 suggests always using `"""` for consistency.  I've been doing it wrong all along!

**Comment by benanne** [comment]
I changed them to `"""` when I merged #135 :)

**Comment by dnouri** [comment]
-1 on one commit per file.  This way we're thrashing the commit history.  I think we can deal with doing whitespace changes without breaking code.

**Comment by benanne** [comment]
Fair point. That said, we haven't exactly paid attention to the commit history before this... if we want to start doing this we should discuss it in a separate issue, and form a consensus about how far we want to go with this. Personally I'm not entirely convinced that doing everything that's possible in order to get a "clean history" is always worth it, because it can make things a lot harder for contributors (or for us).

Regarding PEP8: maybe we should make a rule to never have PEP8 modifications and other modifications in a single commit / PR. A lot of people seem to add a bunch of PEP8 fixes to their commits, presumably because their editors are complaining about stuff and they can't resist fixing it :) If we're going to clean up our act we should probably start asking those changes to be submitted separately.

Of course, once we've finished our sweep across the current codebase to make it PEP8 compliant, this issue should rarely occur in the future.

**Comment by craffel** [comment]
PR: #150

**Comment by benanne** [comment]
I will close this since the codebase should now be PEP8-compliant, and Travis should check any future commits and PRs. For any future discussions regarding code 'aesthetics', and which PEP8 rules we should and should not follow, please create new, separate issues :)
