### ISSUE TITLE
imports of nntools.layers.cuda_convnet and .cormm should fail gracefully

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#53]
`nntools/layers/__init__.py` currently imports the submodules `cuda_convnet` and `cormm` automatically, but these both fail if no GPU is available, and currently this is not caught. The only way to get it working is to comment out both of these imports.

Obviously both of these modules are not usable if no GPU is available, but `import nntools` should not fail because of this. This should trigger a warning at most (probably not even that), and then fail at runtime if any of the GPU-dependent code is called directly.

What is the cleanest way to handle this? I know the Theano codebase has some conventions for optional dependencies, should we inherit those or should we handle this in a different way? Suggestions are welcome!

**Comment by dnouri** [comment]
I guess this has been fixed now through #114.

**Comment by benanne** [comment]
Yep, good catch!
