### ISSUE TITLE
Feedback alignment

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#59]
I'd like to try out feedback alignment, a recently proposed alternative to backprop. http://arxiv.org/abs/1411.0247

In short, this algorithm uses random fixed matrices to backpropagate the error signal, and supposedly works at least as well as backprop. Pretty intruiging!

Implementing it is rather easy, if you implement the backward pass manually. The latter is precisely what Theano allows us to avoid, and I'm wondering if there's a way to implement feedback alignment in a sufficiently general way, so we can leverage as much of Theano's automatic differentiation infrastructure as possible.

It's not just a question of using `theano.clone` to swap out weight matrices with random feedback matrices where appropriate, because the weight matrices are still used for forward propagation. So some would have to be replaced, some wouldn't.

Does anybody have any ideas or insights about this? It would be great to have something with the same interface as the functions in `nntools.updates`, except it does feedback alignment instead of backprop. Is this feasible?

**Comment by f0k** [comment]
> Does anybody have any ideas or insights about this?

You can use `theano.OpFromGraph` on the subgraph for the forward pass of a layer, and then monkey-patch the `grad` method of the returned Op to do something different for the backward pass. We did that for some experiment and it works pretty well. This could even be seamlessly encapsulated in a `FBADenseLayer` class or something.
