### ISSUE TITLE
RFC: Variable naming conventions

### ISSUE THREAD

**Issue by craffel** [benanne/Lasagne#82]
Usually I try to use descriptive variable names wherever possible. I think in general there's no reason to prefer terse code at the sacrifice of readability. One exception (which is not really an exception) is using math variable names when they are (nearly) universal  -- for example, 3.14159265359 should be `pi` not `circumference_divided_by_diameter`. Similarly, it's ok to use `W` and `b` for weight matrix/bias vectors because they are nearly universal. However, in my opinion it's best not to follow the math variable names exactly when there are not standard ones.

I think as more and more people contribute, we should try to fix on a variable naming convention.  This has come up in #17; @skaae is using Graves' notation for LSTM variable names (e.g. `W_hi`) whereas I'm using longer descriptive names (`W_hidden_to_input_gate`). Let's come to a consensus!

**Comment by skaae** [comment]
@craffel:  Should i create a pull request and you can add comments?
