### ISSUE TITLE
make Layer.create_param accept symbolic variables instead of just shared variables

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#83]
Currently, parameters can be initialized with a numpy array, a callable that generates a numpy array, or an already prepared shared variable (the latter is useful to support parameter sharing between several layers for example).

But sometimes you don't actually want your parameters to be shared variables, for example when want to optimize a network by interfacing with scipy's L-BFGS implementation (or another external optimizer). In that case, the parameters are going to be inputs and outputs of a Theano function, so they shouldn't be shared variables to begin with.

The fix is easy, just replace the type check for `SharedVariable` with a superclass that also encompasses symbolic variables (but not arbitrary parameter expressions, as things could get hairy then - see #11). Does this have any other implications though? Are there any other features that are likely to break if we add support for this? Obviously it's a pretty specialized use case, but it could come up, and it doesn't seem to require any major changes to support it.

**Comment by f0k** [comment]
Alternatively, people can always use `theano.clone()` or `theano.compile.pfunc.rebuild_collect_shared()` to replace all parameters in the network output expression with symbolic variables. We could also provide a helper method that does it, possibly even turning all the parameters into correctly reshaped slices of a single long symbolic parameter vector (that's helpful for interfacing with some optimization libraries). But we can still hold off until we actually need this.

**Comment by benanne** [comment]
Yeah, very good point. That might be a more pragmatic solution, and since it's not a very common use case I would be in favour of that.

But I agree, let's figure this out when we need it :)

**Comment by benanne** [comment]
I'll close this for now, but in the long term it would be great to add some helper code for interfacing with external optimizers such as scipy.optimize. I really like the idea of adding a helper function that slices a single parameter vector. Anyway, let's worry about that later.
