### ISSUE TITLE
Learned activation units

### ISSUE THREAD

**Issue by skaae** [benanne/Lasagne#85]
Is there any interested in having learned activation units added to lasagne? I have implemented it at it seems to work. http://arxiv.org/abs/1412.6830

Each unit is a function of S line segments. The slope of each line segment is learned. S is a hyperparameter.

```PYTHON
def LAunit(num_units,
           segments=5,
           init_a=Uniform((-0.05, 0.05)),
           init_b=Uniform((-0.05, 0.05))):
    a = theano.shared(init_a(shape=(num_units, segments)))
    b = theano.shared(init_b(shape=(num_units, segments)))
    rec = lambda x: (x + abs(x)) * 0.5 

    def la_act(act):
        return rec(act) + T.sum(rec(-act.dimshuffle(0, 1, 'x') + 
                                   b.dimshuffle('x', 0, 1)) *  a.dimshuffle('x', 0, 1), 
                                   axis=2)

    return la_act, a, b
```

You call the LAunit function which returns a `la_act`, the activation function,  and the parameters `a` and `b`. The returned 'la_act' can be used as other activation functions. The user setup update rules for `a` and `b` 

```PYTHON
# use Learned activation in mnist
non_lin1, a1, b1 = LAunit(num_hidden_units)
    la_vals.append(a1)
    la_vals.append(b1)
    l_hidden1 = nntools.layers.DenseLayer(l_in, num_units=num_hidden_units, 
                                  nonlinearity=non_lin1)

...
# setup LAunit parameter updates
updates_la_vals = nntools.updates.nesterov_momentum(
        loss_train, la_vals, learning_rate, momentum, weight_decay=0.001)
updates.extend(updates_la_vals)
```

**Comment by benanne** [comment]
I don't really see the benefit of this over maxout to be honest, which is conceptually much simpler. But if people want to experiment with this we can add it.

I'd probably want the implementation to look a bit different than what you posted though, it make more sense to me to have a Layer class that takes care of this (sort of like maxout is implemented with a `FeaturePoolingLayer` stacked on top of a `DenseLayer`). The proposed implementation has parameter variables that are external to the layers, which kind of defeats the point of keeping track of all the parameter variables within the layers.

**Comment by skaae** [comment]
I think this is conceptually simpler :) I think the main idea is that the LA unit in some cases requires less parameters.

I thougt about creating a layer, but creating a non liniearity is more flexible especially if you want to regularize the LA unit parameters but not other weight updates.

**Comment by diogo149** [comment]
@skaae shouldn't that be a * rec(-act + b)

**Comment by skaae** [comment]
isn't it already?

**Comment by diogo149** [comment]
My apologies, I misread (didn't see the parens, and was wondering why you were multiplying two parameters).

**Comment by skaae** [comment]
No problem. I had to remove all the dimshuffles to ser what I had done

**Comment by christopher-beckham** [comment]
@skaae I am also interested in doing the same. Have you figured out how this can be done (easily) for individual neurons in the network?

**Comment by skaae** [comment]
Its much easier to wrap learned activation in a layer.
