### ISSUE TITLE
Saxe style gain for Uniform Glorot Initialization

### ISSUE THREAD

**Issue by cancan101** [benanne/Lasagne#87]
Currently it exists for [Orthogonal](https://github.com/benanne/Lasagne/blob/6f23af2cd948b00a30c1428798a73ce0ab123dfb/lasagne/init.py#L95) but not `Uniform`.

**Comment by benanne** [comment]
Good point. It might actually be cleaner to split up the current `Uniform` initializer into two separate classes, one that takes a range as input, and one that does the Glorot-style initialization (with an optional gain argument).

**Comment by cancan101** [comment]
I agree. I think composition is cleaner than having a lot of extra arguments to something a simple as `Uniform`.

**Comment by benanne** [comment]
This has been addressed in #180. You can specify a gain when using the `GlorotUniform` or `GlorotNormal` initializers.
