### ISSUE TITLE
Strides for convolution and pooling

### ISSUE THREAD

**Issue by run2** [benanne/Lasagne#88]
Hi
First, thanks for this wonderful wrapper.
Can we please have the functionality for strided convolution and pooling ?

Regards

**Comment by benanne** [comment]
Strided convolution is already supported, `Conv2DLayer` has a 'strides' argument. `Conv2DCCLayer` (the cuda-convnet version) supports it as well.

For strided pooling, you can use `MaxPool2DCCLayer` (the cuda-convnet version), but be aware that it has some pretty strict limitations: it only accepts square input and square pooling regions, among other things.

Strided pooling support in Theano is lacking at the moment and this is something that needs to be solved at that level before we can wrap it. I believe the cudnn implementation supports it now, so we will probably implement a `Conv2DDNNLayer` and a `MaxPool2DDNNLayer` at some point :)

**Comment by run2** [comment]
Hey - thanks for that info. I could not use the MaxPool2DCCLayer because of those (square) limitations.

**Comment by benanne** [comment]
It should be fairly straightforward to write a version of `MaxPool2DLayer` that uses `theano.sandbox.cuda.dnn.dnn_pool`. If you end up doing this feel free to send a pull request. If not then we'll probably get around to that fairly soon anyway. See also #50.

**Comment by run2** [comment]
Hey thanks for that. I would love to get my hands on it - but if you are on it then that's great.

**Comment by benanne** [comment]
See #91 :) I can't try it myself at the moment, I'll add some tests and merge it when I can. But feel free to try it out in the meantime.

**Comment by eickenberg** [comment]
Ah, btw, I made a workaround to be able to use strides using the standard `theano.tensor.signal.downsample.maxpool_2d` several times (minimum necessary, least common multiple of pool shape and stride size) and then downsampling appropriately. Probably horribly slow, but at least it provides the functionality if one wants to have it on CPU to play around with.

https://gist.github.com/eickenberg/7e2e7e620b246ca34551

**Comment by benanne** [comment]
Cool! Another way to get overlapping pooling in Theano is to use `T.set_subtensor` with slicing in a for loop, for example as in pylearn2: https://github.com/lisa-lab/pylearn2/blob/14b2f8bebce7cc938cfa93e640008128e05945c1/pylearn2/expr/stochastic_pool.py#L23
This is stochastic pooling. but the same could work for regular max or mean pooling. It's pretty damn slow though (but it works on both CPU and GPU).
