### ISSUE TITLE
Installing Lasagne Uninstalls Theano

### ISSUE THREAD

**Issue by cancan101** [benanne/Lasagne#89]
I have Theano installed using `python setup.py develop`. 

When I check `/usr/local/lib/python2.7/dist-packages/easy-install.pth`, I see:
```
/home/ubuntu/git/Theano
```

When I run: `python setup.py install` for Lasagne, I see the following:
```
Searching for Theano==0.6.0
Best match: Theano 0.6.0
Processing Theano-0.6.0-py2.7.egg
Removing Theano 0.6.0 from easy-install.pth file
Adding Theano 0.6.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg
```

and then this file is broken  `/usr/local/lib/python2.7/dist-packages/easy-install.pth`:
```
./Theano-0.6.0-py2.7.egg
```

and theano no longer imports.

**Comment by cancan101** [comment]
This looks to be caused by an extraneous folder `/usr/local/lib/python2.7/dist-packages/Theano-0.6.0-py2.7.egg`. After deleting it, the install seems to work.

**Comment by dnouri** [comment]
By the way, the right way to install Lasagne is described in here: https://github.com/benanne/Lasagne/blob/master/docs/user/installation.rst (see "Install from source").  That'll give you a recent enough copy of Theano.

**Comment by cancan101** [comment]
I have some locally changes to Theano that I am experimenting with so I wanted to install Theano in `develop` mode from my local source. It looks like when I moved from `install` mode to `develop` mode it left some residual folders around that are confusing `setup.py`.

**Comment by f0k** [comment]
An easy trick is to run `pip uninstall Theano` (or whatever package you're dealing with) before running `setup.py` again. This should work regardless of whether you installed it via `pip`, and it will avoid any problems caused by switching between `install` and `develop`.

**Comment by dnouri** [comment]
Tried to reproduce this.  Here's what I did:
```bash
daniel:~$ virtualenv lasagne --system-site-packages
daniel:~$ cd lasagne/
daniel:~/lasagne$ git clone git@github.com:Theano/Theano.git
daniel:~/lasagne$ git clone git@github.com:benanne/Lasagne.git
daniel:~/lasagne$ . bin/activate
(lasagne)daniel:~/lasagne$ cd Theano/
(lasagne)daniel:~/lasagne/Theano$ python setup.py develop
(lasagne)daniel:~/lasagne/Theano$ cd ../Lasagne/
(lasagne)daniel:~/lasagne/Lasagne$ python setup.py develop
...
Best match: Theano 0.6.0
Theano 0.6.0 is already the active version in easy-install.pth
...
```

So it looks like using another install of Theano from somewhere else is working fine for me.  Maybe @cancan101 can provide some steps to reproduce?
