### ISSUE TITLE
Allow `border_mode` to be a tuple of integers for `Conv2DLayer`

### ISSUE THREAD

**Issue by benanne** [benanne/Lasagne#90]
So I had a go at implementing the `Conv2DDNNLayer`, and I realised that our `Conv2DLayer` already has a `convolution` keyword argument, which allows for `theano.tensor.nnet.conv2d` to be replaced with `theano.sandbox.cuda.dnn_conv`.

The only thing it doesn't support is passing a tuple of integers to the `border_mode` argument, which is kind of the main reason we'd want a separate layer for `dnn_conv` to begin with.

So instead, it might make more sense to modify `Conv2DLayer` so tuples can be passed in, and then make it complain about that only if the default Theano convolution is used. What does everyone think?

Related to that, the current `Conv2DCCLayer` has two arguments, `border_mode` and `pad`. The former can be used to pass in the strings 'valid', 'same' or 'full', and the latter can be used to pass an integer (cuda-convnet does not support different amounts of padding in the x and y directions so it was pointless to make this a tuple). These two arguments cannot be used together.

So it might be better to modify this code as well to merge `border_mode` and `pad` into a single argument (called `border_mode`), for consistency, which supports both string values and tuples of integers. This will break existing code that uses the `pad` argument, but at this stage I suppose that's not such a big deal (or we can leave it in an deprecate it, but I'm not sure if we want to start cluttering our codebase like that already).

Thoughts?

We could also consider implementing manual padding in `Conv2DLayer` for the case where a tuple is specified and the default Theano convolution is used.

**Comment by f0k** [comment]
> So it might be better to modify this code as well to merge `border_mode` and `pad` into a single argument (called `border_mode`), for consistency, which supports both string values and tuples of integers.

Yes, that's exactly what should happen upstream (in Theano, I mean: https://github.com/Theano/Theano/issues/2118#issuecomment-58160895).

> I realised that our `Conv2DLayer` already has a `convolution` keyword argument

It will call that with `image_shape` and `filter_shape` keyword arguments, though. I think Theano's `conv2d()` is the only one that supports these.

**Comment by dimatura** [comment]
By the way, Conv2DMM layer causes deprecation warnings from theano's `BaseGpuCorrMM` op about not using `pad`, and to use `border_mode` instead.

FWIW, I wrote a simple Conv2D layer using the `dnn` stuff from the Theano sandbox. I definitely got a performance boost relative to the cuda-convnet layer.

**Comment by benanne** [comment]
Cool! Feel free to send a pull request :)

**Comment by benanne** [comment]
I'm going to close this since it doesn't make sense to do it for the vanilla theano convolution right now, and since dnn_conv will have its own class soon (see #93).

**Comment by f0k** [comment]
> I also agree that this is something that needs to happen upstream, but who knows when that will happen

Well, we don't have to wait for anything to happen upstream, we can make it happen ourselves. Theano is just as open as Lasagne. It's way more complex, but contributing back may still be a better use of time than implementing workarounds.
