### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MartinThoma** [benanne/Lasagne#92]
Hallo benanne,

## Hosting Documentation Online
did you know that you can let the documentation be hosted?

```bash
$ python setup.py upload_docs --upload-dir docs/_build/html
```

will automatically upload it to http://pythonhosted.org/lasagne/

By adding

```text
.. image:: http://img.shields.io/badge/docs-latest-brightgreen.svg
    :target: http://pythonhosted.org/lasagne/
```

to your README.rst you can inform others who see the GitHub repository of the documentation.

## Contents

Could you please finish the tutorial? The 'Understand the MNIST example' seems to be a TODO.

**Comment by MartinThoma** [comment]
Oh, yes, it should also be on PyPI. Why don't you want to add it?

Just run

```python
$ python setup.py register
```

See: https://docs.python.org/2/distutils/packageindex.html

**Comment by benanne** [comment]
Lasagne is still under very heavy development. It has barely any documentation and limited test coverage, so we are not ready to make a release at this point. Or are you saying that making a release is not required to registered it on PyPI? I was under the impression that it was.

**Comment by MartinThoma** [comment]
What do you mean by 'making a release'?

By the way, I am currently writing a very similar package (see https://github.com/MartinThoma/nntoolkit).
Could you please send me an email (info@martin-thoma.de)? I would like to talk about some design decisions and it feels strange to write that in an issue :-)

**Comment by benanne** [comment]
What I meant is that we are not ready to release "Lasagne 0.1". Currently everyone is using the latest revision from this repository. I was under the impression that putting a package on PyPI implies that you "release" it, i.e. you package up a certain version of the code and people will install that version if they type "pip install Lasagne". I feel we do not yet have a version of the code that is suitable for this. There is some work to be done :)

Feel free to contact me at sanderdieleman@gmail.com.

**Comment by MartinThoma** [comment]
> What I meant is that we are not ready to release "Lasagne 0.1".

Oh, ok. Yes, that needs to be done.

**Comment by f0k** [comment]
> Sweet! We don't have a lot of documentation yet, but I Guess it couldn't hurt to set this up.

We could also have it hosted on readthedocs.org; github provides a hook to auto-update it on pushing to the repository: https://github.com/rtfd/readthedocs.org. I am under the impression that this is what most Python projects are using these days.

**Comment by benanne** [comment]
If that doesn't require a PyPI release it may be a better bet :) It would definitely be convenient to have what's available be easily accessible on the web already.

**Comment by f0k** [comment]
Yes, it's completely independent of PyPI. [By default](https://read-the-docs.readthedocs.org/en/latest/versions.html), it will build documentation for the `master` branch plus documentation for any releases (indicated by tags, just as on github).

**Comment by benanne** [comment]
Alright, I'll give this a try!

**Comment by benanne** [comment]
Here we go :) http://lasagne.readthedocs.org/

**Comment by MartinThoma** [comment]
Nice! Thank you very much!

**Comment by f0k** [comment]
Cool, that was quick!

**Comment by benanne** [comment]
I'll close this to avoid confusion with the other 'documentation' issue.
