### ISSUE TITLE
We cannot obtain consistent hidden layer outputs with nondeterminism

### ISSUE THREAD

**Issue by f0k** [benanne/Lasagne#97]
It just occurred to me that we have a problem in how the noise layers are implemented and in how `get_output()` works. Assume that we have a deep neural network with some noise layers (e.g., dropout) in between, and assume that we want to obtain the outputs of not just the output layer, but one or more hidden layers. A possible use case might be investigating the transformation of data in the forward pass, or regularizing the central layer of an auto-encoder.
Now what one would probably do in Lasagne would be something like:
```python
input = lasagne.layers.InputLayer(...)
hidden = lasagne.layers.dropout(input)
output = lasagne.layers.DenseLayer(hidden)
cost = something(hidden.get_output()) + something_else(output.get_output())
```
Does anybody see the problem yet? Watch and observe:
```python
In [1]: import lasagne
Using gpu device 0: GeForce GT 640

In [2]: input = lasagne.layers.InputLayer((2,5))

In [3]: hidden = lasagne.layers.dropout(input)

In [4]: import numpy as np

In [5]: import theano

In [6]: output = lasagne.layers.DenseLayer(hidden, 5, W=np.eye(5, dtype=theano.config.floatX))

In [7]: f = theano.function([input.input_var], [hidden.get_output(), output.get_output()])

In [8]: f(np.ones((2,5), dtype=theano.config.floatX))
Out[8]: 
[array([[ 0.,  0.,  2.,  0.,  2.],
       [ 2.,  0.,  0.,  0.,  0.]], dtype=float32),
 array([[ 0.,  2.,  2.,  2.,  0.],
       [ 2.,  2.,  2.,  2.,  0.]], dtype=float32)]
```
So this actually does two separate forward passes with different dropout masks.
a) I don't think this is what people usually want.
b) There's currently no way to obtain the outputs of different layers for the same forward pass. Note that this also applies to networks with multiple output layers.

To solve point b), we could implement a way to have `get_output` return the output not only for the layer it's called on, but also for all or some layers before that; or a helper function that returns the outputs for a given list of layers; or anything in between.
To solve point a), we would need to cache the dropout mask per input and reuse it if it already exists. This would also solve point b), but by relying on the layer implementations to give exactly the same graph for each call to `get_output()` rather than by providing a data propagation method that includes the intermediate expressions.

So, should we solve this (I think yes, we clearly should) and if so, how?

**Comment by benanne** [comment]
Interesting! I guess we could give `get_output` an additional argument which accepts a list of layers for which the activations need to be returned.

I don't think point  a) as you formulate it needs solving - the fact that this is only being discovered now indicates that it's a fairly uncommon use case, so I don't see the problem in requiring the use of the extra argument on `get_output` for that. Caching dropout masks sounds really, really icky :p

**Comment by dimatura** [comment]
Good catch. I am actually using this kind of network structure to combine information from different resolutions in image inputs. It "works", but now I see that this problem is probably making the minimization problem harder because of the subtle inconsistencies caused by different dropout masks. There should be definitely be some way to avoid this, but I'm not sure how to yet either.

**Comment by dimatura** [comment]
@benanne I think your suggestion for the `get_output` call makes sense. The caffe python wrapper does something similar, except the requested outputs ("blobs") are specified by their key (which indexes into an OrderedDict).

**Comment by benanne** [comment]
Ah, that's interesting :) I guess in this case the keys are just the layer instances.

**Comment by f0k** [comment]
> I don't think point a) as you formulate it needs solving - the fact that this is only being discovered now indicates that it's a fairly uncommon use case

It could just as well indicate that it's difficult to find, because mostly everything will work. And as to "only being disovered now": I don't know how large the active user base of Lasagne is, but I'm only now in the process of converting my tool chain to use it and discovered the problem by thinking about that.

> It "works", but now I see that this problem is probably making the minimization problem harder because of the subtle inconsistencies caused by different dropout masks.

I guess it won't change the minimization problem a lot, but it will be a whole lot slower because many computations have to be repeated for each different mask.

> Caching dropout masks sounds really, really icky :p

It wouldn't be that much of a problem, we could keep them in a `WeakValueDictionary` so they would be deleted whenever there's no graph alive that references them. The only problem I see is that the subtleties of the requirement "Each call to `get_output_for()` with the same parameters must return the same or an exactly equivalent expression" are a bit difficult to communicate to developers. It would only affect nondeterministic layers, though, and it would prevent duplicate forward pass computations for all users, no matter if they know about this issue or not (remember that this issue will usually go by unnoticed, it will just cause worse performance).

Extending `get_output` would be more elegant (the intermediate expressions are built anyway, so why shouldn't we just use these), but I still don't think we should leave the trap open for the unsuspecting.

**Comment by benanne** [comment]
Fair points. I agree that enforcing this constraint for `get_output_for` is going to be infeasible with nondeterministic layers, so I'm also in favour of adding an extra argument to `get_output` and clearly documenting this pitfall.

Regarding caching dropout masks: are we 100% certain that there are no use cases where you would want different dropout masks for the same input? Overall I don't think `Layer` classes should have state.

**Comment by f0k** [comment]
> Regarding caching dropout masks: are we 100% certain that there are no use cases where you would want different dropout masks for the same input?

If I had a use case for that, intuitively, I would have created two separate dropout layers.

**Comment by benanne** [comment]
Instead of caching dropout masks, maybe we should be considering memoization of outputs (for all layers). It seems like this could also fix the issue currently being discussed in #17 (slower execution resulting from Theano executing the same scan twice because the expressions are not merged). I haven't thought this through at all though.

**Comment by craffel** [comment]
In #17, I wrote 

>  There is a gaussian noise layer on the input in the LSTM benchmark, but this issue is there whether or not the noise layer is present.

Just to be clear on this point - actually, when the noise layer is not present, it merges the `scan` correctly, but it still doesn't merge the `grad_of_scan`, which makes it a little faster but still slower than the hacked `ElemwiseSumLayer` (see https://github.com/benanne/Lasagne/issues/17#issuecomment-70380257).  So, yeah, this issue is pretty closely related to the output memoization/deterministic issue brought up elsewhere.

With input noise layer:
```
Ops
---
  23.2%    23.2%      72.327s       3.62e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}
  22.3%    45.5%      69.544s       3.48e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}
  15.0%    60.6%      46.804s       2.34e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn}
  14.5%    75.1%      45.318s       2.27e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn}
   6.6%    81.7%      20.538s       1.03e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn}
   6.4%    88.0%      19.786s       9.89e-01s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn}
   3.1%    91.1%       9.632s       4.82e-01s     Py      20        1   forall_inplace,gpu,scan_fn&scan_fn&scan_fn&scan_fn}
   2.8%    94.0%       8.793s       4.40e-01s     Py      20        1   forall_inplace,gpu,scan_fn&scan_fn&scan_fn&scan_fn}
   1.8%    95.8%       5.666s       2.83e-01s     Py      20        1   forall_inplace,gpu,scan_fn&scan_fn}
   1.7%    97.5%       5.241s       2.62e-01s     Py      20        1   forall_inplace,gpu,scan_fn&scan_fn}
   0.9%    98.3%       2.737s       1.37e-01s     Py      20        1   forall_inplace,gpu,scan_fn}
   0.8%    99.2%       2.538s       1.27e-01s     Py      20        1   forall_inplace,gpu,scan_fn}
```

Without input noise layer:
```
Ops
---
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Op name>
  23.9%    23.9%      62.239s       3.11e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}
  23.4%    47.4%      60.964s       3.05e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn&grad_of_scan_fn}
  16.1%    63.5%      41.935s       2.10e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn}
  15.8%    79.3%      41.109s       2.06e+00s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn&grad_of_scan_fn}
   7.3%    86.6%      19.026s       9.51e-01s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn}
   7.1%    93.7%      18.356s       9.18e-01s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn}
   2.9%    96.6%       7.534s       1.26e-01s     Py      60        3   forall_inplace,gpu,scan_fn}
   2.7%    99.3%       7.024s       1.17e-01s     Py      60        3   forall_inplace,gpu,scan_fn}
```

With input noise layer and hack `ElemwiseSumLayer` from https://github.com/benanne/Lasagne/issues/17#issuecomment-70380257:

```
Ops
---
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Op name>
  31.3%    31.3%      40.990s       1.02e+00s     Py      40        2   forall_inplace,gpu,grad_of_scan_fn}
  31.0%    62.3%      40.525s       1.01e+00s     Py      40        2   forall_inplace,gpu,grad_of_scan_fn}
  13.0%    75.3%      17.002s       8.50e-01s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn}
  12.6%    87.8%      16.467s       8.23e-01s     Py      20        1   forall_inplace,gpu,grad_of_scan_fn}
   5.8%    93.6%       7.575s       1.26e-01s     Py      60        3   forall_inplace,gpu,scan_fn}
   5.4%    99.0%       7.025s       1.17e-01s     Py      60        3   forall_inplace,gpu,scan_fn}
```

**Comment by f0k** [comment]
Closing because the discussion has been moved to #104, a different manifestation of the same problem.
