### ISSUE TITLE
Conv1DLayer settings?

### ISSUE THREAD

**Issue by skaae** [benanne/Lasagne#98]
What is the input requirements for Conv1DLayer?

I tried with data with shape  (batch_size, n_features) ? 

I want to use convolutions with the recurrent layer. My idea is to have a 1d convolution that is same size as n_features and let the RNN slide the convolutions accros the sequence.

Is there a better option than conv1d?

**Comment by benanne** [comment]
You closed this so I guess you've figured it out in the meantime? For a 1D convolutional layer the input size should be (batch_size, n_features, length).

**Comment by skaae** [comment]
No not really, but I figure what i wanted to do corresponded to a Denselayer :)
