### ISSUE TITLE
Allow Setting num_units=0 to turn off a layer

### ISSUE THREAD

**Issue by cancan101** [benanne/Lasagne#99]
Allow Setting `num_units=0` or `=None` to turn off a layer.

This would allow [GridSearch per this comment](http://danielnouri.org/notes/2014/12/17/using-convolutional-neural-nets-to-detect-facial-keypoints-tutorial/#comment-1755383265)
to search over a set of values including the choice to turn off the layer:
```python
from sklearn.grid_search import GridSearchCV
parameters = {'hidden_num_units': [0, 50, 100, 200]}
gs = GridSearchCV(net1, parameters)
gs.fit(X, y)
print gs.grid_scores_
```

**Comment by f0k** [comment]
Phew. Firstly, this would only apply to a `DenseLayer`, others don't have a `num_units` parameter, so there's no way to implement this in a consistent way for all layers. Secondly, it's unclear what should happen for `num_units=None`: Just copy over the output as-is? Still flatten it, because it's a dense layer? Still apply the nonlinearity or not?
I think this isn't anything that the `lasagne.layers` classes should cope with. It would be easy enough to write your own wrapper class that "disables" a layer in the way you need it depending on some keyword argument. We could also provide such a wrapper class with Lasagne if we think it would be generally useful. But I wouldn't start to agument existing Layer classes with ways to bridge/disable them.

**Comment by cancan101** [comment]
I agree that dealing with `"num_units=0` -> disable layer" does not have to be something that `lasagne.layers` has to deal with; rather, it can be left to the user. 

In order to make writing this logic easier, I would suggest a PassThrough that can be used which would just pass through values in forward and backward pass. (Potentially this layer can already be constructed using `MultipleInputsLayer`?).

Then the user can do something like:
```
def maybe_dense(num_units, *args, **kwargs):
   if num_units == 0:
      return PassThrough()
   else:
     return DenseLayer(num_units, *args, **kwargs)
```

Also, I think that `num_units=0` can be generalized to the convolutional layers as well.

**Comment by benanne** [comment]
I guess it could be useful to have a layer that just returns its input (and it's trivial to implement). Not sure if I like the name `PassThrough` though, maybe `PassThroughLayer`, or `DummyLayer`, or `IdentityLayer` or something like that.

**Comment by cancan101** [comment]
Sure, all of those names sound better.

**Comment by f0k** [comment]
Hooray, a vote! :) +1 for `IdentityLayer`. Note that you missed the `input_layer` parameter in your `maybe_dense()` example.

**Comment by craffel** [comment]
I've used [hyperopt](https://github.com/hyperopt/hyperopt) to tune the hyperparameters (including # of layers) of a `lasagne`-based neural net; I just rebuilt a new network for each hyperparameter setting.   If you change the number of units in a layer, you need to rebuild the neural net also; I don't think it's such a bad thing to have to rebuild the net with one fewer layer for each hyperparameter setting.  Either way, it sort of sounds like you're talking about two different things - one is a way to make a layer pass its input unmodified, the other is a layer which passes its input unmodified.  In the latter case, you'd still need to rebuild the net to swap out the layers (I think).

**Comment by f0k** [comment]
> Note that you missed the `input_layer` parameter in your `maybe_dense()` example.

Reading this again after @craffel's comment, note that your example would actually become:

```python
def maybe_dense(input_layer, num_units, *args, **kwargs):
    if num_units == 0:
        return input_layer
    else:
        return DenseLayer(input_layer, num_units, *args, **kwargs)
```

There's no need for a dummy layer at all.

**Comment by cancan101** [comment]
That seems a lot easier :-).
